In [1]:
import numpy as np

In [2]:
a_list= [1,2,3,4,5, [1,2,3], "temat"] # nie idealna lista
k_krotka = (1,2,3,4,5, [1,2,3], "temat")
b_list = [1,2,3,4,5]
n_array = np.array(b_list) # wektor numpy


In [3]:
a_list+b_list
n_array+n_array

array([ 2,  4,  6,  8, 10])

In [4]:
a_list[3]

4

In [5]:
a_list.append(100)
print(a_list)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100]


In [6]:
k_krotka[4]

5

In [7]:
k_krotka.append(100)

AttributeError: 'tuple' object has no attribute 'append'

In [8]:
np.array(b_list)+np.array(b_list)

array([ 2,  4,  6,  8, 10])

In [9]:
n_array = np.array(a_list) # wektor numpy

In [10]:
n_array

array([1, 2, 3, 4, 5, list([1, 2, 3]), 'temat'], dtype=object)

In [70]:
#### Nowosci

studenci_slownik = {123: 123,"Igor":3, "Frankek":5, "Zosia":22,"Julia":[2,21], (1,2):"Krotka"}

In [71]:
print(studenci_slownik)

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka'}


In [72]:
studenci_slownik["Zosia"]

22

In [11]:
for elementy in studenci_slownik:
    print(elementy)

print("*"*20)
for elementy in studenci_slownik.keys():
    print(elementy)

123
Igor
Frankek
Zosia
Julia
(1, 2)
********************
123
Igor
Frankek
Zosia
Julia
(1, 2)


In [12]:
for elementy in studenci_slownik.items():
    print(elementy)

(123, 123)
('Igor', 3)
('Frankek', 5)
('Zosia', 22)
('Julia', [2, 21])
((1, 2), 'Krotka')


In [13]:
for elementy in studenci_slownik.values():
    print(elementy)

123
3
5
22
[2, 21]
Krotka


In [14]:
studenci_slownik["Cuthulu"]= -1000000

In [15]:
studenci_slownik

{123: 123,
 'Igor': 3,
 'Frankek': 5,
 'Zosia': 22,
 'Julia': [2, 21],
 (1, 2): 'Krotka',
 'Cuthulu': -1000000}

In [16]:
automatyczna_lista=[liczba**2 for liczba in range(100) if liczba%4==0]
print(automatyczna_lista)

[0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296, 1600, 1936, 2304, 2704, 3136, 3600, 4096, 4624, 5184, 5776, 6400, 7056, 7744, 8464, 9216]


In [17]:
studenci = studenci_slownik.keys()
automatyczny_slownik=dict(para for para in enumerate(studenci))
print(automatyczny_slownik)

{0: 123, 1: 'Igor', 2: 'Frankek', 3: 'Zosia', 4: 'Julia', 5: (1, 2), 6: 'Cuthulu'}


In [18]:
##### zbiory

a={1,2,3,"Franek"}
b={2,3,4,"Franek"}


In [19]:
a|b #suma zbiorów, sum of sets

{1, 2, 3, 4, 'Franek'}

In [20]:
a.add("Franek")
print(a)

{1, 2, 3, 'Franek'}


In [25]:
1 in a
"Igor" in studenci_slownik

True

### Własne typy

In [21]:
zajecia = [["wf"],
           ["informatyka", "nauka czytania"],
           ["relax", "jedzenie"],
           ["mispy","mispy w domu"],
           ["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"]
          ]

dnityg= ["Pon","Wto","Sro","Czwar","Pio"]

def dodaj_dwie_liczby(liczba1,liczba2):
    return liczba1+liczba2

In [176]:
class DzienZajec():
    """obiekt trzymający dany dzień zajęć i przypisane mu metody"""
    
    
    def __init__(self, lista_na_dany_dzien, nazwa_dnia): #definicja
        self.lista_zajec= lista_na_dany_dzien
        self.dzien = nazwa_dnia
        

    
    def ile_mispow(self):
        ile_m = sum([1 for zajecie in self.lista_zajec if "misp" in zajecie.lower()])
        return ile_m

    @property #zamienia na wlasciwosc   
    def ile_zajec(self):
        return len(self.lista_zajec)
    
    def __repr__(self):
        zajecia_do_stringa = ", ".join(self.lista_zajec)
        return "W dzien {} mam zajecia: {}".format(self.dzien, zajecia_do_stringa)
    

In [177]:
pio_zajecia = DzienZajec(["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"],
                        "piatek")

In [178]:
pio_zajecia.ile_zajec

4

In [102]:
print(pio_zajecia)

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu


In [34]:
pio_zajecia.lista_zajec

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu']

In [34]:
pio_zajecia.lista_zajec.append("MISP")
print(pio_zajecia.lista_zajec)

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [35]:
pio_zajecia.ile_mispow()

4

In [95]:
print(pio_zajecia.lista_zajec)


['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [85]:
pio_zajecia

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu, MISP

In [105]:
print(pio_zajecia.ile_zajec)

5


In [108]:
lista_zajec= [DzienZajec(lista_dzien, dzien) for lista_dzien, dzien in 
             zip(zajecia,dnityg)]

In [109]:
print(lista_zajec)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [112]:
posortowane_po_zajeciach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_zajec)
posortowane_po_mispach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_mispow())

In [113]:
print(posortowane_po_zajeciach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [114]:
print(posortowane_po_mispach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


# Challenge 1

Stworz typ NumerTelefonu

 -- przy tworzeniu sprawdza czy właściwy numer (Polski) jeśli nie pisze, że error (ew. Exception)
 
 -- gdy printuję to mi pisze polskimi słowami i.e. "jeden, pięć, siedem, zero"
 
 -- gdy wywołuję właściwość wojewodzwtwo, podaje mi wojewodztwo ew. ze to komorkowy
 
 

In [ ]:
# ma na takie rzeczy być w stanie odpowiedzieć

numer_lodz = NumerTelefonu("426877868")
>>> "prawidlowy numer"

numer_lodz.wojewodztwo 
>>> "Lodz"

print(numer_lodz)
>>> "cztery dwa sześć osiem siedem siedem osiem sześć osiem"

In [1]:
lista={75:"Dolnośląskie",76:"Dolnośląskie",74:"Dolnośląskie",71:"Dolnośląskie",
        52:"Kujawsko-pomorskie",56:"Kujawsko-pomorskie",54:"Kujawsko-pomorskie",
        83:"Lubelskie",82:"Lubelskie",81:"Lubelskie",84:"Lubelskie",
        95:"Lubuskie",68:"Lubuskie",
        42:"Łódzkie",44:"Łódzkie",43:"Łódzkie",46:"Łódzkie",
        12:"Małopolskie",18:"Małopolskie",14:"Małopolskie",
        23:"Mazowieckie",29:"Mazowieckie",24:"Mazowieckie",48:"Mazowieckie",25:"Mazowieckie",22:"Mazowieckie",
        77:"Opolskie",
        13:"Podkarpackie",16:"Podkarpackie",17:"Podkarpackie",15:"Podkarpackie",
        85:"Podlaskie",86:"Podlaskie",87:"Podlaskie",
        58:"Pomorskie",59:"Pomorskie",
        33:"Śląskie",34:"Śląskie",32:"Śląskie",
        41:"Świętokrzyskie",
        55:"Warmińsko-mazurskie",89:"Warmińsko-mazurskie",
        62:"Wielkopolskie",63:"Wielkopolskie",65:"Wielkopolskie",67:"Wielkopolskie",61:"Wielkopolskie",
        94:"Zachodnio-pomorskie",91:"Zachodnio-pomorskie"}

litery={0:"zero",1:"jeden",2:"dwa",3:"trzy",4:"cztery",5:"pięć",6:"sześć",7:"siedem",8:"osiem",9:"dziewięć"}

class NumerTelefonu():
    
    def __init__(self, numer):
        self.num= numer
        if len(self.num) != 9:
            print("Niepoprawna długość numeru")
            
        if int(self.num[:2]) not in lista.keys():
            print("Numer nie pochodzi z PL")
            
        if len(self.num) == 9 and (int(self.num[:2]) in lista.keys()):
            print("Numer poprawny")
            
    @property
    def wojewodztwo(self):
        if len(self.num) == 9 and (int(self.num[:2]) in lista.keys()):
            return lista[int(self.num[:2])]
        
    def __repr__(self):
        numer_cyfry=[]
        for litera in self.num:
            numer_cyfry.append(litera)
            
        przeliterowane=[]
        for cyfra in numer_cyfry:
            przeliterowane.append(litery[int(cyfra)])
            
        return " {} ".format(przeliterowane)

In [2]:
nr2=NumerTelefonu("426788778")

Numer poprawny


In [3]:
nr2.wojewodztwo

'Łódzkie'

In [4]:
print(nr2)

 ['cztery', 'dwa', 'sześć', 'siedem', 'osiem', 'osiem', 'siedem', 'siedem', 'osiem'] 
